basePath: /
definitions:
  app.authUsers:
    properties:
      refresh:
        type: string
    required:
    - refresh
    type: object
  app.email:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  structure.User:
    properties:
      email:
        type: string
      uuid:
        type: string
    required:
    - uuid
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: API server for authorisation
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TODO App API
  version: "1.0"
paths:
  /about:
    get:
      description: Get information about authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Get user info
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      description: Login by UUID and receive JWT tokens
      parameters:
      - description: User UUID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/structure.User'
      produces:
      - application/json
      responses:
        "201":
          description: Tokens successfully created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Auth
  /logout:
    get:
      description: Invalidate user's session
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Logout user
      tags:
      - Auth
  /refresh:
    post:
      consumes:
      - application/json
      description: Refresh access and refresh tokens
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.authUsers'
      produces:
      - application/json
      responses:
        "200":
          description: Tokens successfully refreshed
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Refresh tokens
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Register user by email and receive UUID
      parameters:
      - description: User email
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.email'
      produces:
      - application/json
      responses:
        "200":
          description: User successfully registered
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Validation error
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: User already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
